version: '3.8'
services:

  app:
    image: node:18-alpine
    volumes:
      - ./server/generated:/app/server
    working_dir: /app/server
    command: npm start
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: top_secret99
      MYSQL_DB: codeblocks

  mysql: 
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: top_secret99
      MYSQL_DB: codeblocks
    container_name: moveo-db
    volumes:
        - ./server/generating_db/:/docker-entrypoint-initdb.d
        #above works with local


volumes:
  data: 
  